packages:
  - apps/*
  - packages/*
allowBuilds:
  esbuild: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - "@better-auth/core@1.6.25"
  - "@better-auth/drizzle-adapter@1.6.25"
  - "@better-auth/expo@1.6.25"
  - "@better-auth/kysely-adapter@1.6.25"
  - "@better-auth/memory-adapter@1.6.25"
  - "@better-auth/mongo-adapter@1.6.25"
  - "@better-auth/prisma-adapter@1.6.25"
  - "@better-auth/telemetry@1.6.25"
  - better-auth@1.6.25
