/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,jsx,ts,tsx}",
    "./components/**/*.{js,jsx,ts,tsx}",
    "../../packages/design-system/src/**/*.{js,jsx,ts,tsx}",
  ],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        canvas: "#FCF8F2",
        gutter: "#F8F1EA",
        paper: "#FFFDF8",
        placeholder: "#F0E9DF",
        ink: "#151515",
        muted: "#6F6B64",
        accent: "#6651B8",
        "accent-pressed": "#504093",
        "accent-soft": "#C8B8F0",
        "coral-text": "#A94838",
        "aqua-text": "#176C68",
        line: "#E2D9CD",
        control: "#8E877D",
        disabled: "#E5E0D8",
        selected: "#EEE9FA",
        "selected-border": "#7864C8",
        coral: "#F3A995",
        lilac: "#C8B8F0",
        aqua: "#9FD8D0",
        success: "#17633A",
        "success-soft": "#EEF7F1",
        warning: "#855510",
        "warning-soft": "#FFF8E7",
        error: "#A1261A",
        "error-soft": "#FFF1EE",
        danger: "#A1261A",
      },
      borderRadius: {
        todam: "10px",
        panel: "18px",
        media: "16px",
      },
      fontFamily: {
        sans: ['"Work Sans"', "system-ui", "sans-serif"],
        serif: ['"Playfair Display"', "Georgia", "serif"],
      },
      boxShadow: {
        soft: "0 16px 42px rgba(43, 34, 27, 0.09)",
        lift: "0 22px 54px rgba(65, 48, 92, 0.13)",
        lilac: "0 12px 36px rgba(120, 100, 200, 0.16)",
      },
      maxWidth: {
        content: "1120px",
      },
    },
  },
  plugins: [],
};
